### ISSUE TITLE
cannot load such file

### ISSUE THREAD

**Issue by derpyderpydo** [james-ransom/hn-delete-negative-point-comments#1]
$ ruby -v
ruby 2.6.0p0 (2018-12-25 revision 66547) [x86_64-linux]

$ gem -v
3.0.1

and I'm getting the following:

```
$ ruby test.rb 
Traceback (most recent call last):
        4: from test.rb:2:in `<main>'
        3: from test.rb:2:in `load'
        2: from watch.rb:1:in `<top (required)>'
        1: from /usr/local/lib/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/lib/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- rest-client (LoadError)
```

**Comment by derpyderpydo** [comment]
also:  

$ ruby test.rb 
Traceback (most recent call last):
        4: from test.rb:2:in `<main>'
        3: from test.rb:2:in `load'
        2: from watch.rb:1:in `<top (required)>'
        1: from /usr/share/rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/share/rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- rest-client (LoadError)

**Comment by derpyderpydo** [comment]
apologies for spamming:

gem install rest-client fixed my above issues.
